### ISSUE TITLE
[BUG] - GMT+/- issue

### ISSUE THREAD

**Issue by donald-sick** [SICKAppSpaceCodingStarterKit/CSK_Module_DateTime#1]
2 issues:
1. The GMT+/- is not working properly. 
2. Using GMT+/- is not applicable for those has day light saving.

**CSK module:**
 - Version: 3.0.0

**AppSpace device used:**
 - SIM2500

**To Reproduce**  
1. On Australia Melbourne time zone
3. Select GMT+10, it is only 1 hour later than GMT
4. Select GMT+1 is 10 hour different from GMT

**Expected behavior**  
Select Australia/Melbourne in the list instead of GMT+10. Time Zone will change between GMT+10 and GMT+11 for day light saving. 

**Additional context**  
DateTime.setTimeZone() supports IANA tz database format. The string 'GMT+1' is not IANA tz database format. So the design is wrong.

**Comment by golluroSICKAG** [comment]
Thank you for your bug report!
So far we just created these timezones as in the past there was an issue, that not all possible timezones (like 'Australia/Melbourne') were accepted by all devices, so we just limited the scope to these "Etc/GMT" zones.
But I will check this issue again and will try to find out if this can be improved / fixed.

**Comment by golluroSICKAG** [comment]
Hi!

I pushed a new version of the DateTime module, see this [PR](https://github.com/SICKAppSpaceCodingStarterKit/CSK_Module_DateTime/pull/2)
In this version it is possible to set a custom timezone via UI. The UI will respond if it was successful or not. So it should be possible to use e.g. "Australia/Melbourne" as timezone now.

Beside of this, 2 more things:
- Related to [this page](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) it seems that the "Etc/GMT..." timezones are canonical (primary, preferred zone name). Do you agree with this?
- Is it possible that your described behaviour is related to the fact, that these "Etc/GMT..." timezones are "intentionally inverted", as described in [this link](https://en.wikipedia.org/wiki/Tz_database#Area):
"The special area of "Etc" is used for some administrative zones, particularly for "Etc/UTC" which represents [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time). In order to conform with the [POSIX](https://en.wikipedia.org/wiki/POSIX) style, those zone names beginning with "Etc/GMT" have their sign reversed from the standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) convention. In the "Etc" area, zones west of GMT have a positive sign and those east have a negative sign in their name (e.g "Etc/GMT-14" is 14 hours ahead of GMT)."

**Comment by donald-sick** [comment]
Tested the new version. 

1. Run the CSK_Module_DateTime in the AppStudio simulator. It is the only app running.
2. Open the page, both the 'Select timezone' dropdown and 'Custom timezone' input box are showing 'Australia/Sydney'
3. Change input box to 'Australia/Melbourne' then click Set Time button
4. The dropdown and input box are set back to 'Australia/Sydney'

Expected behaviour:
The input box won't change and dropdown is set to 'Australia/Melbourne'

**Comment by golluroSICKAG** [comment]
Please check following steps:

- Please try to change the timezone BEFORE anything else, especially before it is connected to a NTP server. So maybe deactivate NTP if it was active, reboot the device and then try to change the timezone.
- There should be an UI feedback if it worked to set the timezone or if it did not work.
- Do you run the [CSK logger module](https://github.com/SICKAppSpaceCodingStarterKit/CSK_1stModule_Logger) and did you check the log feedback?
- Does it work to set another timezone?

**Comment by donald-sick** [comment]
Tested on SIM2500, everything works as expected. My previous test was on emulator which doesn't have permission to change Windows timezone I guess.

**Comment by golluroSICKAG** [comment]
That sounds great!
After an internal review this update will be merged.
Kind regards!
